<?php

/**
 * @file
 * Defines the product option entity and associated features.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function commerce_option_theme() {
  return [
    'commerce_option_option_value' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for product option value templates.
 *
 * Default template: commerce-option-option-value.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_commerce_option_option_value(array &$variables) {
  /** @var Drupal\commerce_option\Entity\ProductOptionValueInterface $product */
  $attribute_value = $variables['elements']['#commerce_option_option_value'];

  $variables['option_value_entity'] = $attribute_value;
  $variables['option_value'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['option_value'][$key] = $variables['elements'][$key];
  }
}
