<?php

/**
 * @file
 * Defines the product option entity and associated features.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function commerce_option_theme() {
  return [
    'commerce_option_option_value' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for product option value templates.
 *
 * Default template: commerce-option-option-value.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing rendered fields.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_commerce_option_option_value(array &$variables) {
  /** @var Drupal\commerce_option\Entity\ProductOptionValueInterface $product */
  $option_value = $variables['elements']['#commerce_option_option_value'];

  $variables['option_value_entity'] = $option_value;
  $variables['option_value'] = [];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['option_value'][$key] = $variables['elements'][$key];
  }
}

/**
 * Inserts an array value into a specific position in another array.
 *
 * @param $arrayValueToPosition
 *   Array value to position.
 * @param $wholeArray
 *   Array to position into.
 * @param $position
 *   The position number.
 *
 * @return array
 *   Merged array
 */
function positionArrayElement($arrayValueToPosition, $wholeArray, $position) {
  $firstPart = array_slice($wholeArray, 0, $position);
  $lastPart = array_slice($wholeArray, $position, count($wholeArray) - $position);

  return array_merge($firstPart, $arrayValueToPosition, $lastPart);
}

/**
 * Implements hook_entity_type_build().
 */
function commerce_option_entity_type_build(array &$entity_types) {
  $entity_types['commerce_order_item']->setFormClass(
    'add_to_cart', '\Drupal\commerce_option\Form\AddToCartForm'
  );
}
